import type { Metadata } from "next";
import { Inter, Poppins, Proza_Libre, Cardo } from "next/font/google";
import { AnimatePresence, motion } from "framer-motion";
import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Indiscoveries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>

      <body className={inter.className}>
        <Navbar />
          <div className="w-full mx-auto">{children}</div>
          <SpeedInsights/>
        <Footer />
      </body>
    </html>
  );
}
